/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ClickableTooltip {
        "opened": boolean;
        "text": string;
        "timer": number;
    }
    interface UcSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLClickableTooltipElement extends Components.ClickableTooltip, HTMLStencilElement {
    }
    var HTMLClickableTooltipElement: {
        prototype: HTMLClickableTooltipElement;
        new (): HTMLClickableTooltipElement;
    };
    interface HTMLUcSideDrawerElement extends Components.UcSideDrawer, HTMLStencilElement {
    }
    var HTMLUcSideDrawerElement: {
        prototype: HTMLUcSideDrawerElement;
        new (): HTMLUcSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "clickable-tooltip": HTMLClickableTooltipElement;
        "uc-side-drawer": HTMLUcSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface ClickableTooltip {
        "opened"?: boolean;
        "text"?: string;
        "timer"?: number;
    }
    interface UcSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "clickable-tooltip": ClickableTooltip;
        "uc-side-drawer": UcSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "clickable-tooltip": LocalJSX.ClickableTooltip & JSXBase.HTMLAttributes<HTMLClickableTooltipElement>;
            "uc-side-drawer": LocalJSX.UcSideDrawer & JSXBase.HTMLAttributes<HTMLUcSideDrawerElement>;
        }
    }
}
